name: FusionSolar Data Fetcher

on:
  schedule:
    - cron: '0 */1 * * *'  # Esegue lo script ogni ora
  workflow_dispatch:        # Permette l'avvio manuale dal pannello GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Esegui main.py
        env:
          FUSIONSOLAR_API_USER: ${{ secrets.FUSIONSOLAR_API_USER }}
          FUSIONSOLAR_API_KEY: ${{ secrets.FUSIONSOLAR_API_KEY }}
        run: python main.py
